pluginManagement { repositories { google(); mavenCentral(); maven { url 'https://raw.githubusercontent.com/alexgreench/google-webrtc/master' }; gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name='MalawiHubTeacher'
include ':app'
