package mw.malawihub.connector;

import android.Manifest;import android.app.Activity;import android.os.Bundle;import android.content.Intent;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.view.View;import android.widget.*;import java.io.*;import java.net.*;import org.json.*;

public class MainActivity extends Activity {
 static final String API="https://cdqrdovgdidzxmyygoee.supabase.co/functions/v1/business-device"; static final int SMS_REQUEST=10; EditText code; TextView status; Button connect,permissions,settings; android.content.SharedPreferences prefs;
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("hub",0); LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(36,50,36,30);
 TextView h=new TextView(this);h.setText("MalawiHub Business Connector");h.setTextSize(24);h.setTextColor(Color.rgb(21,32,51));box.addView(h);TextView i=new TextView(this);i.setText("Connect this phone to your Business Hub. SMS access is used only to monitor supported Airtel Money and Mpamba transaction messages.");i.setPadding(0,20,0,20);box.addView(i);
 code=new EditText(this);code.setHint("6-digit pairing code");code.setInputType(2);box.addView(code);connect=new Button(this);connect.setText("Connect to Business Hub");box.addView(connect);permissions=new Button(this);permissions.setText("Enable SMS access");permissions.setVisibility(View.GONE);box.addView(permissions);settings=new Button(this);settings.setText("Open app settings");settings.setVisibility(View.GONE);box.addView(settings);status=new TextView(this);status.setPadding(0,20,0,0);box.addView(status);setContentView(box);
 permissions.setOnClickListener(v->requestSms());settings.setOnClickListener(v->openSettings());connect.setOnClickListener(v->claim());updateStatus(); }
 boolean smsReady(){return android.os.Build.VERSION.SDK_INT<23 || (checkSelfPermission(Manifest.permission.RECEIVE_SMS)==PackageManager.PERMISSION_GRANTED && checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED);}
 void updateStatus(){boolean paired=prefs.getString("token","").length()>0;if(paired){if(smsReady()){status.setText("✓ Connected and SMS access is enabled. Monitoring is ready.");permissions.setVisibility(View.GONE);settings.setVisibility(View.GONE);}else{status.setText("✓ Phone is connected, but SMS access is not enabled. Tap Enable SMS access to continue.");permissions.setVisibility(View.VISIBLE);settings.setVisibility(View.GONE);}}else{status.setText("Not connected. Enter the 6-digit pairing code from Business Hub.");permissions.setVisibility(View.GONE);settings.setVisibility(View.GONE);}}
 void requestSms(){if(android.os.Build.VERSION.SDK_INT<23){updateStatus();return;}java.util.ArrayList<String> missing=new java.util.ArrayList<>();if(checkSelfPermission(Manifest.permission.RECEIVE_SMS)!=PackageManager.PERMISSION_GRANTED)missing.add(Manifest.permission.RECEIVE_SMS);if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED)missing.add(Manifest.permission.READ_SMS);if(missing.isEmpty()){updateStatus();return;}requestPermissions(missing.toArray(new String[0]),SMS_REQUEST);}
 @Override public void onRequestPermissionsResult(int requestCode,String[] perms,int[] results){super.onRequestPermissionsResult(requestCode,perms,results);if(requestCode==SMS_REQUEST){if(smsReady()){status.setText("✓ Connected and SMS access is enabled. Monitoring is ready.");permissions.setVisibility(View.GONE);settings.setVisibility(View.GONE);}else{status.setText("SMS access is still required. Tap Enable SMS access again. If Android no longer shows the permission prompt, open app settings and enable SMS permissions there.");permissions.setVisibility(View.VISIBLE);settings.setVisibility(View.VISIBLE);}}}
 @Override protected void onResume(){super.onResume();if(prefs!=null)updateStatus();}
 void openSettings(){try{Intent i=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);i.setData(Uri.parse("package:"+getPackageName()));startActivity(i);}catch(Exception e){status.setText("Open Android Settings and enable SMS permissions for MalawiHub Business Connector.");}}
 void claim(){String c=code.getText().toString().trim();if(c.length()!=6){status.setText("Enter the 6-digit code from Business Hub.");return;}connect.setEnabled(false);status.setText("Connecting…");new Thread(()->{try{HttpURLConnection x=(HttpURLConnection)new URL(API).openConnection();x.setRequestMethod("POST");x.setDoOutput(true);x.setConnectTimeout(15000);x.setReadTimeout(15000);x.setRequestProperty("Content-Type","application/json");String body=new JSONObject().put("action","claim").put("pairing_code",c).put("device_name",android.os.Build.MANUFACTURER+" "+android.os.Build.MODEL).toString();try(OutputStream o=x.getOutputStream()){o.write(body.getBytes("UTF-8"));}int response=x.getResponseCode();String r=read(x);JSONObject j=new JSONObject(r);if(response>=300)throw new Exception(j.optString("error","Connection failed"));String token=j.optString("device_token","");String deviceId=j.optString("device_id","");if(token.length()==0||deviceId.length()==0)throw new Exception("Server did not return a device connection token");prefs.edit().putString("token",token).putString("device_id",deviceId).apply();runOnUiThread(()->{connect.setEnabled(true);status.setText("✓ Connected. Now enable SMS access.");requestSms();});}catch(Exception e){runOnUiThread(()->{connect.setEnabled(true);status.setText("Connection failed: "+e.getMessage());});}}).start();}
 static String read(HttpURLConnection x)throws Exception{InputStream in=x.getResponseCode()<300?x.getInputStream():x.getErrorStream();if(in==null)return "{}";ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] q=new byte[2048];int n;while((n=in.read(q))>0)b.write(q,0,n);return b.toString("UTF-8");}
}
