package mw.malawihub.connector;

import android.Manifest;import android.app.Activity;import android.os.Bundle;import android.content.pm.PackageManager;import android.graphics.Color;import android.view.View;import android.widget.*;import java.io.*;import java.net.*;import org.json.*;

public class MainActivity extends Activity {
 static final String API="https://cdqrdovgdidzxmyygoee.supabase.co/functions/v1/business-device"; EditText code; TextView status; android.content.SharedPreferences prefs;
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("hub",0); LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(36,50,36,30);
 TextView h=new TextView(this);h.setText("MalawiHub Business Connector");h.setTextSize(24);h.setTextColor(Color.rgb(21,32,51));box.addView(h);TextView i=new TextView(this);i.setText("Connect this phone to your Business Hub, then allow SMS access. Only supported Airtel Money/Mpamba transaction details are sent.");i.setPadding(0,20,0,20);box.addView(i);
 code=new EditText(this);code.setHint("6-digit pairing code");code.setInputType(2);box.addView(code);Button connect=new Button(this);connect.setText("Connect to Business Hub");box.addView(connect);status=new TextView(this);status.setPadding(0,20,0,0);box.addView(status);setContentView(box);
 if(prefs.getString("token","").length()>0){status.setText("✓ Phone connected. SMS monitoring is ready.");requestSms();} connect.setOnClickListener(v->claim()); }
 void requestSms(){if(android.os.Build.VERSION.SDK_INT>=23 && checkSelfPermission(Manifest.permission.RECEIVE_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECEIVE_SMS,Manifest.permission.READ_SMS},10);}
 void claim(){String c=code.getText().toString().trim();if(c.length()!=6){status.setText("Enter the 6-digit code from Business Hub.");return;}status.setText("Connecting…");new Thread(()->{try{HttpURLConnection x=(HttpURLConnection)new URL(API).openConnection();x.setRequestMethod("POST");x.setDoOutput(true);x.setRequestProperty("Content-Type","application/json");String body=new JSONObject().put("action","claim").put("pairing_code",c).put("device_name",android.os.Build.MANUFACTURER+" "+android.os.Build.MODEL).toString();try(OutputStream o=x.getOutputStream()){o.write(body.getBytes("UTF-8"));}String r=read(x);JSONObject j=new JSONObject(r);if(x.getResponseCode()>=300)throw new Exception(j.optString("error","Connection failed"));prefs.edit().putString("token",j.getString("device_token")).putString("device_id",j.getString("device_id")).apply();runOnUiThread(()->{status.setText("✓ Connected. Allow SMS access when Android asks.");requestSms();});}catch(Exception e){runOnUiThread(()->status.setText("Connection failed: "+e.getMessage()));}}).start();}
 static String read(HttpURLConnection x)throws Exception{InputStream in=x.getResponseCode()<300?x.getInputStream():x.getErrorStream();ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] q=new byte[2048];int n;while((n=in.read(q))>0)b.write(q,0,n);return b.toString("UTF-8");}
}
