package mw.malawihub.connector;

import android.content.*;import android.provider.Telephony;import android.telephony.SmsMessage;import java.io.*;import java.net.*;import java.security.*;import java.util.*;import org.json.*;

public class SmsReceiver extends BroadcastReceiver {
 static final String API="https://cdqrdovgdidzxmyygoee.supabase.co/functions/v1/business-device";
 public void onReceive(Context c,Intent in){if(!Telephony.Sms.Intents.SMS_RECEIVED_ACTION.equals(in.getAction()))return;android.content.SharedPreferences p=c.getSharedPreferences("hub",0);String token=p.getString("token","");if(token.isEmpty())return;for(SmsMessage s:Telephony.Sms.Intents.getMessagesFromIntent(in)){String body=s.getMessageBody()==null?"":s.getMessageBody();String low=body.toLowerCase(Locale.ROOT);String provider=low.contains("mpamba")||low.contains("tnm")?"mpamba":low.contains("airtel")?"airtel_money":null;if(provider==null)continue;send(c,token,provider,body);}}
 static void send(Context c,String token,String provider,String body){new Thread(()->{try{String type="transaction";String l=body.toLowerCase(Locale.ROOT);if(l.contains("received")||l.contains("deposit")||l.contains("credited"))type="received";else if(l.contains("sent")||l.contains("withdraw")||l.contains("debited"))type="sent";Double amount=numberNear(body,new String[]{"received","sent","amount","deposit","withdraw","credited","debited"});Double balance=numberNear(body,new String[]{"balance","available balance","new balance","remaining"});String ref=ref(body);String event=new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.US).format(new Date());String summary=provider+" "+type+(amount!=null?" — MWK "+amount:"")+(balance!=null?" — displayed balance: MWK "+balance:"");JSONObject j=new JSONObject().put("provider",provider).put("transaction_type",type).put("amount",amount).put("balance",balance).put("reference",ref).put("event_at",event).put("message",summary).put("raw_hash",sha(body));HttpURLConnection x=(HttpURLConnection)new URL(API).openConnection();x.setRequestMethod("POST");x.setDoOutput(true);x.setRequestProperty("Content-Type","application/json");x.setRequestProperty("Authorization","Bearer "+token);try(OutputStream o=x.getOutputStream()){o.write(new JSONObject().put("action","ingest").put("provider",provider).put("transaction_type",type).put("amount",amount).put("balance",balance).put("reference",ref).put("event_at",event).put("message",summary).put("raw_hash",sha(body)).toString().getBytes("UTF-8"));}x.getResponseCode();x.disconnect();}catch(Exception ignored){}}).start();}
 static Double numberNear(String s,String[] words){String[] parts=s.replace(",","").split("\\s+");for(int i=0;i<parts.length;i++){String w=parts[i].toLowerCase(Locale.ROOT);for(String key:words)if(w.contains(key)){for(int j=Math.max(0,i-2);j<=Math.min(parts.length-1,i+3);j++){String n=parts[j].replaceAll("[^0-9.]","");if(!n.isEmpty())try{return Double.valueOf(n);}catch(Exception ignored){}}}}return null;}
 static String ref(String s){java.util.regex.Matcher m=java.util.regex.Pattern.compile("(?i)(?:ref(?:erence)?|transaction)\\s*[:#-]?\\s*([A-Z0-9-]{4,30})").matcher(s);return m.find()?m.group(1):null;}
 static String sha(String s)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");byte[] b=d.digest(s.getBytes("UTF-8"));StringBuilder x=new StringBuilder();for(byte q:b)x.append(String.format("%02x",q));return x.toString();}
}
