plugins { id 'com.android.application' }

android {
    namespace 'mw.malawihub.keyboard'
    compileSdk 36
    defaultConfig {
        applicationId 'mw.malawihub.keyboard'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        debug { applicationIdSuffix '.debug'; versionNameSuffix '-debug' }
        release { minifyEnabled false; shrinkResources false; debuggable false }
    }
}
